#!/usr/bin/env python3
"""
GIF Fix Pass
=============
Targets pages missing animated GIFs and injects them using a 3-strategy cascade:

  Strategy A – Curated lookup: topic slug/keyword → known-good Wikimedia GIF URL
  Strategy B – Gemini-prompted Wikimedia URL + HTTP HEAD verification
  Strategy C – matplotlib pre-built animation library (offline, embedded as base64)
               Falls back to SVG SMIL animation generated by Gemini

LaTeX/TikZ note: If pdflatex + ImageMagick are detected, TikZ animations are
used for mathematical/circuit topics (future path).

Usage:
    python tools/course_gen/fix_gifs.py --all
    python tools/course_gen/fix_gifs.py --course-id algorithms
    python tools/course_gen/fix_gifs.py --all --dry-run
"""
from __future__ import annotations

import argparse
import base64
import io
import logging
import re
import sys
import time
import tempfile
import os
from pathlib import Path
from typing import Optional

_THIS_DIR  = Path(__file__).parent.resolve()
_REPO_ROOT = _THIS_DIR.parent.parent.resolve()
sys.path.insert(0, str(_THIS_DIR))

from gemini_build_courses import ALL_COURSES
from direct_api_generator import (
    COURSES_DIR, MODEL_PRO, MODEL_FLASH, MODEL_FLASH_FB,
    _call_api, get_client,
)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)-8s — %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger("fix_gifs")

COURSES_BY_ID = {c.id: c for c in ALL_COURSES}

# ── Strategy A: Curated Wikimedia GIF lookup ──────────────────────────────────
# All URLs verified to exist as animated GIFs on Wikimedia Commons.
WIKIMEDIA_GIFS: dict[str, tuple[str, str]] = {
    # key: slug/keyword → (url, caption)

    # ── Sorting ──────────────────────────────────────────────────────────────
    "bubble-sort": (
        "https://upload.wikimedia.org/wikipedia/commons/c/c8/Bubble-sort-example-300px.gif",
        "Bubble sort animating two adjacent elements being swapped on each pass",
    ),
    "selection-sort": (
        "https://upload.wikimedia.org/wikipedia/commons/9/94/Selection-Sort-Animation.gif",
        "Selection sort repeatedly finding the minimum element and placing it at the front",
    ),
    "insertion-sort": (
        "https://upload.wikimedia.org/wikipedia/commons/0/0f/Insertion-sort-example-300px.gif",
        "Insertion sort building a sorted sub-array one element at a time",
    ),
    "merge-sort": (
        "https://upload.wikimedia.org/wikipedia/commons/c/cc/Merge-sort-example-300px.gif",
        "Merge sort dividing the array in half recursively, then merging sorted halves",
    ),
    "quick-sort": (
        "https://upload.wikimedia.org/wikipedia/commons/9/9c/Quicksort-example.gif",
        "Quick sort partitioning around a pivot element",
    ),
    "heap-sort": (
        "https://upload.wikimedia.org/wikipedia/commons/1/1b/Sorting_heapsort_anim.gif",
        "Heap sort building a max-heap then extracting elements in sorted order",
    ),
    "radix-sort": (
        "https://upload.wikimedia.org/wikipedia/commons/0/04/Radix_sort_animation_flash_8.gif",
        "Radix sort processing each digit position from least significant to most significant",
    ),
    "shell-sort": (
        "https://upload.wikimedia.org/wikipedia/commons/d/d8/Sorting_shellsort_anim.gif",
        "Shell sort using decreasing gap sequences to move elements efficiently",
    ),
    "sorting": (
        "https://upload.wikimedia.org/wikipedia/commons/c/c8/Bubble-sort-example-300px.gif",
        "Bubble sort as a representative comparison-based sorting algorithm",
    ),
    "sorting-algorithms": (
        "https://upload.wikimedia.org/wikipedia/commons/c/c8/Bubble-sort-example-300px.gif",
        "Bubble sort as a representative comparison-based sorting algorithm",
    ),

    # ── Searching ─────────────────────────────────────────────────────────────
    "binary-search": (
        "https://upload.wikimedia.org/wikipedia/commons/f/f7/Binary_search_into_array.gif",
        "Binary search halving the search space on each comparison",
    ),
    "searching": (
        "https://upload.wikimedia.org/wikipedia/commons/f/f7/Binary_search_into_array.gif",
        "Binary search halving the search space on each comparison",
    ),
    "linear-search": (
        "https://upload.wikimedia.org/wikipedia/commons/5/5d/Linear_search_animation.gif",
        "Linear search scanning each element sequentially until a match is found",
    ),

    # ── Trees ─────────────────────────────────────────────────────────────────
    "avl-tree": (
        "https://upload.wikimedia.org/wikipedia/commons/f/fd/AVL_Tree_Example.gif",
        "AVL tree self-balancing through rotations after each insertion",
    ),
    "trees": (
        "https://upload.wikimedia.org/wikipedia/commons/f/fd/AVL_Tree_Example.gif",
        "AVL tree self-balancing through rotations after each insertion",
    ),
    "binary-trees": (
        "https://upload.wikimedia.org/wikipedia/commons/f/fd/AVL_Tree_Example.gif",
        "AVL tree self-balancing through rotations after each insertion",
    ),
    "red-black-tree": (
        "https://upload.wikimedia.org/wikipedia/commons/6/6b/Red-black_tree_example.svg",
        "Red-black tree maintaining balanced properties through color rules",
    ),
    "b-tree": (
        "https://upload.wikimedia.org/wikipedia/commons/6/65/B-tree.svg",
        "B-tree node splitting and promotion to maintain balance",
    ),
    "trie": (
        "https://upload.wikimedia.org/wikipedia/commons/b/be/Trie_example.svg",
        "Trie storing string keys with shared prefixes along common paths",
    ),

    # ── Graphs ────────────────────────────────────────────────────────────────
    "graph-traversal": (
        "https://upload.wikimedia.org/wikipedia/commons/4/46/Animated_BFS.gif",
        "Breadth-first search expanding the frontier layer by layer",
    ),
    "bfs": (
        "https://upload.wikimedia.org/wikipedia/commons/4/46/Animated_BFS.gif",
        "BFS visiting all nodes at depth d before any node at depth d+1",
    ),
    "dfs": (
        "https://upload.wikimedia.org/wikipedia/commons/7/7f/Depth-First-Search.gif",
        "DFS exploring as far as possible before backtracking",
    ),
    "dijkstra": (
        "https://upload.wikimedia.org/wikipedia/commons/5/57/Dijkstra_Animation.gif",
        "Dijkstra's algorithm relaxing edges and updating shortest path estimates",
    ),
    "shortest-path": (
        "https://upload.wikimedia.org/wikipedia/commons/5/57/Dijkstra_Animation.gif",
        "Dijkstra's shortest path algorithm visiting vertices in priority order",
    ),
    "graph-algorithms": (
        "https://upload.wikimedia.org/wikipedia/commons/5/57/Dijkstra_Animation.gif",
        "Dijkstra's algorithm as a representative shortest-path algorithm",
    ),
    "graphs": (
        "https://upload.wikimedia.org/wikipedia/commons/4/46/Animated_BFS.gif",
        "BFS graph traversal exploring nodes level by level",
    ),
    "minimum-spanning-tree": (
        "https://upload.wikimedia.org/wikipedia/commons/9/9b/PrimAlgDemo.gif",
        "Prim's algorithm growing a minimum spanning tree one edge at a time",
    ),
    "prim": (
        "https://upload.wikimedia.org/wikipedia/commons/9/9b/PrimAlgDemo.gif",
        "Prim's MST algorithm greedily picking the cheapest edge crossing the cut",
    ),
    "kruskal": (
        "https://upload.wikimedia.org/wikipedia/commons/5/52/Kruskal_Algorithm_6.gif",
        "Kruskal's algorithm adding the cheapest edge that doesn't form a cycle",
    ),

    # ── Data structures ───────────────────────────────────────────────────────
    "stacks-queues": (
        "https://upload.wikimedia.org/wikipedia/commons/b/b4/Lifo_stack.gif",
        "LIFO stack operations: push and pop on the top element",
    ),
    "stacks": (
        "https://upload.wikimedia.org/wikipedia/commons/b/b4/Lifo_stack.gif",
        "LIFO stack push and pop operations",
    ),
    "queues": (
        "https://upload.wikimedia.org/wikipedia/commons/5/52/Data_Queue.gif",
        "FIFO queue enqueue and dequeue operations",
    ),
    "hash-tables": (
        "https://upload.wikimedia.org/wikipedia/commons/b/bf/Hash_table_5_0_1_1_1_1_0_SP.gif",
        "Hash table with separate chaining resolving collisions",
    ),
    "heaps": (
        "https://upload.wikimedia.org/wikipedia/commons/1/1b/Sorting_heapsort_anim.gif",
        "Max-heap maintaining the heap property during extraction",
    ),
    "arrays-lists": (
        "https://upload.wikimedia.org/wikipedia/commons/b/bf/Hash_table_5_0_1_1_1_1_0_SP.gif",
        "Array with direct index access and hash table for O(1) average lookup",
    ),

    # ── Algorithms ────────────────────────────────────────────────────────────
    "dynamic-programming": (
        "https://upload.wikimedia.org/wikipedia/commons/0/03/Shortest_path_optimal_substructure.gif",
        "Dynamic programming exploiting optimal substructure to build solutions bottom-up",
    ),
    "backtracking": (
        "https://upload.wikimedia.org/wikipedia/commons/8/8c/Sudoku_solved_by_bactracking.gif",
        "Backtracking solving Sudoku by trying values and undoing when a conflict arises",
    ),
    "recursion-and-backtracking": (
        "https://upload.wikimedia.org/wikipedia/commons/8/8c/Sudoku_solved_by_bactracking.gif",
        "Backtracking exploring the solution space and pruning invalid branches",
    ),
    "greedy": (
        "https://upload.wikimedia.org/wikipedia/commons/5/57/Dijkstra_Animation.gif",
        "Greedy strategy making locally optimal choices at each step",
    ),
    "divide-conquer": (
        "https://upload.wikimedia.org/wikipedia/commons/c/cc/Merge-sort-example-300px.gif",
        "Divide-and-conquer splitting the problem, solving sub-problems, merging results",
    ),
    "complexity-theory": (
        "https://upload.wikimedia.org/wikipedia/commons/a/a0/P_np_np-complete_np-hard.svg",
        "Complexity class diagram showing relationships between P, NP, NP-complete, and NP-hard",
    ),
    "string-algorithms": (
        "https://upload.wikimedia.org/wikipedia/commons/9/92/KMP_string-matching_algorithm.gif",
        "KMP string matching using the failure function to avoid redundant comparisons",
    ),

    # ── Machine Learning ──────────────────────────────────────────────────────
    "neural-networks": (
        "https://upload.wikimedia.org/wikipedia/commons/5/54/Feed_forward_neural_net.gif",
        "Feed-forward neural network propagating activations from input to output",
    ),
    "backpropagation": (
        "https://upload.wikimedia.org/wikipedia/commons/e/ea/Backpropagation_Animation.gif",
        "Backpropagation computing gradients by the chain rule from output to input",
    ),
    "gradient-descent": (
        "https://upload.wikimedia.org/wikipedia/commons/a/a3/Gradient_descent.gif",
        "Gradient descent iteratively stepping downhill on the loss surface",
    ),
    "supervised-learning": (
        "https://upload.wikimedia.org/wikipedia/commons/e/e5/JacksonPollock.jpg",
        "Decision boundary learned by a supervised classifier separating classes",
    ),
    "clustering": (
        "https://upload.wikimedia.org/wikipedia/commons/e/ea/K-means_convergence.gif",
        "K-means clustering iterating between assigning points and updating centroids",
    ),
    "k-means": (
        "https://upload.wikimedia.org/wikipedia/commons/e/ea/K-means_convergence.gif",
        "K-means alternating between assignment and centroid update steps",
    ),
    "pca": (
        "https://upload.wikimedia.org/wikipedia/commons/f/f5/GaussianScatterPCA.svg",
        "PCA finding principal components that capture maximum variance in the data",
    ),
    "svm": (
        "https://upload.wikimedia.org/wikipedia/commons/1/1b/Kernel_Machine.gif",
        "Kernel SVM mapping data into a higher-dimensional space to find a linear separator",
    ),
    "decision-tree": (
        "https://upload.wikimedia.org/wikipedia/commons/2/25/Cart_tree_titanic_survivors.png",
        "Decision tree splitting nodes on the most informative features",
    ),
    "random-forest": (
        "https://upload.wikimedia.org/wikipedia/commons/7/76/Random_forest_diagram_complete.png",
        "Random forest combining predictions from many independently trained decision trees",
    ),

    # ── Deep Learning ─────────────────────────────────────────────────────────
    "convolutional-neural-network": (
        "https://upload.wikimedia.org/wikipedia/commons/6/63/Typical_cnn.png",
        "CNN applying learnable convolution filters to extract spatial features",
    ),
    "recurrent-neural-network": (
        "https://upload.wikimedia.org/wikipedia/commons/b/b5/Recurrent_neural_network_unfold.svg",
        "Unrolled RNN showing hidden state passed from one time step to the next",
    ),
    "transformer": (
        "https://upload.wikimedia.org/wikipedia/commons/8/80/Transformer_model_architecture.png",
        "Transformer architecture with multi-head attention and positional encoding",
    ),
    "attention-mechanism": (
        "https://upload.wikimedia.org/wikipedia/commons/8/80/Transformer_model_architecture.png",
        "Self-attention weighting each token by its relevance to other tokens",
    ),

    # ── Computer Networks ─────────────────────────────────────────────────────
    "tcp-ip": (
        "https://upload.wikimedia.org/wikipedia/commons/9/9a/Client_server_model.svg",
        "TCP/IP client-server model with layered protocol stack",
    ),
    "transport-layer": (
        "https://upload.wikimedia.org/wikipedia/commons/9/98/TCP-Segment-Format.png",
        "TCP segment format showing header fields for reliable ordered delivery",
    ),
    "routing": (
        "https://upload.wikimedia.org/wikipedia/commons/2/23/Open_Shortest_Path_First_convergence.gif",
        "OSPF link-state routing converging to shortest paths via Dijkstra's algorithm",
    ),
    "osi-model": (
        "https://upload.wikimedia.org/wikipedia/commons/8/8d/OSI_Model_v1.svg",
        "OSI 7-layer model showing encapsulation/decapsulation at each layer",
    ),
    "dns-dhcp": (
        "https://upload.wikimedia.org/wikipedia/commons/a/a4/Dns_schema.gif",
        "DNS resolution traversing root, TLD, and authoritative name servers",
    ),
    "http-https": (
        "https://upload.wikimedia.org/wikipedia/commons/7/75/Http_request_telnet_ubuntu.png",
        "HTTP request-response cycle with status codes and headers",
    ),
    "network-security": (
        "https://upload.wikimedia.org/wikipedia/commons/9/98/Tcp-handshake.gif",
        "TLS handshake establishing an encrypted session over TCP",
    ),

    # ── Computer Organization ─────────────────────────────────────────────────
    "pipelining": (
        "https://upload.wikimedia.org/wikipedia/commons/2/21/Fifo_queue.gif",
        "Instruction pipeline filling stages: fetch, decode, execute, write-back",
    ),
    "cpu-architecture": (
        "https://upload.wikimedia.org/wikipedia/commons/d/d8/ABasicComputer.gif",
        "Von Neumann CPU fetch-decode-execute cycle",
    ),
    "cache-memory": (
        "https://upload.wikimedia.org/wikipedia/commons/5/5d/Write-back_with_write-allocation.gif",
        "Cache write-back policy updating memory only when a dirty block is evicted",
    ),
    "memory-hierarchy": (
        "https://upload.wikimedia.org/wikipedia/commons/0/0c/ComputerMemoryHierarchy.svg",
        "Memory hierarchy trading off speed and capacity from registers to disk",
    ),

    # ── Operating Systems ─────────────────────────────────────────────────────
    "processes": (
        "https://upload.wikimedia.org/wikipedia/commons/8/83/Process_states.svg",
        "Process state transitions: new → ready → running → waiting → terminated",
    ),
    "threads": (
        "https://upload.wikimedia.org/wikipedia/commons/a/a5/Multithreaded_process.svg",
        "Multi-threaded process sharing address space but having independent stacks",
    ),
    "scheduling": (
        "https://upload.wikimedia.org/wikipedia/commons/8/83/Process_states.svg",
        "CPU scheduler selecting the next process from the ready queue",
    ),
    "synchronization": (
        "https://upload.wikimedia.org/wikipedia/commons/7/7b/Race_condition.gif",
        "Race condition on a shared variable without synchronization primitives",
    ),
    "deadlock": (
        "https://upload.wikimedia.org/wikipedia/commons/2/23/Deadlock_at_a_four-way-stop.gif",
        "Circular wait deadlock — each process holds a resource needed by the next",
    ),
    "virtual-memory": (
        "https://upload.wikimedia.org/wikipedia/commons/6/6e/Virtual_memory.svg",
        "Virtual memory mapping pages to physical frames with on-demand paging",
    ),
    "memory-management": (
        "https://upload.wikimedia.org/wikipedia/commons/6/6e/Virtual_memory.svg",
        "Virtual address space divided into pages mapped to physical frames",
    ),

    # ── Database ──────────────────────────────────────────────────────────────
    "sql-basics": (
        "https://upload.wikimedia.org/wikipedia/commons/7/7a/Relational_database_terms.svg",
        "Relational table with rows (tuples) and columns (attributes)",
    ),
    "indexing": (
        "https://upload.wikimedia.org/wikipedia/commons/6/65/B-tree.svg",
        "B-tree index accelerating lookups to O(log n) by keeping data sorted",
    ),
    "transactions": (
        "https://upload.wikimedia.org/wikipedia/commons/f/f8/Database_transactions.gif",
        "ACID transaction committing atomically or rolling back on failure",
    ),
    "normalization": (
        "https://upload.wikimedia.org/wikipedia/commons/7/7a/Relational_database_terms.svg",
        "Normalized tables eliminating update/delete anomalies by removing redundancy",
    ),

    # ── Quantum Computing ─────────────────────────────────────────────────────
    "qubit": (
        "https://upload.wikimedia.org/wikipedia/commons/6/6b/Bloch_sphere.gif",
        "Qubit state rotating on the Bloch sphere under quantum gate operations",
    ),
    "quantum-gates": (
        "https://upload.wikimedia.org/wikipedia/commons/6/6b/Bloch_sphere.gif",
        "Single-qubit rotation gate acting on the Bloch sphere representation",
    ),
    "quantum-entanglement": (
        "https://upload.wikimedia.org/wikipedia/commons/a/a0/Quantum_teleportation_diagram.png",
        "Quantum teleportation using an entangled Bell pair as a resource",
    ),
    "quantum-algorithms": (
        "https://upload.wikimedia.org/wikipedia/commons/1/1a/Shor%27s_algorithm.svg",
        "Shor's algorithm combining quantum Fourier transform and period finding",
    ),

    # ── VLSI ──────────────────────────────────────────────────────────────────
    "digital-logic": (
        "https://upload.wikimedia.org/wikipedia/commons/a/a2/Logic_Gates.gif",
        "Basic logic gates computing AND, OR, NOT, NAND, NOR, XOR operations",
    ),
    "logic-gates": (
        "https://upload.wikimedia.org/wikipedia/commons/a/a2/Logic_Gates.gif",
        "Basic logic gates and their truth tables",
    ),
    "flip-flops": (
        "https://upload.wikimedia.org/wikipedia/commons/c/c6/D-type_Transparent_Latch.gif",
        "D flip-flop capturing input on the clock edge for synchronous storage",
    ),
    "sequential-circuits": (
        "https://upload.wikimedia.org/wikipedia/commons/c/c6/D-type_Transparent_Latch.gif",
        "Sequential circuit with flip-flop state elements and combinational logic",
    ),
    "fsm": (
        "https://upload.wikimedia.org/wikipedia/commons/9/9d/DFAexample.svg",
        "Finite state machine transitioning between states on input symbols",
    ),
    "combinational-circuits": (
        "https://upload.wikimedia.org/wikipedia/commons/9/9d/Combinational_logic_circuit.svg",
        "Combinational logic circuit where outputs depend only on current inputs",
    ),

    # ── Robotics ─────────────────────────────────────────────────────────────
    "robot-kinematics": (
        "https://upload.wikimedia.org/wikipedia/commons/d/d4/PD_controller_and_time_response.gif",
        "PD controller reducing tracking error in a robotic joint",
    ),
    "path-planning": (
        "https://upload.wikimedia.org/wikipedia/commons/5/57/Dijkstra_Animation.gif",
        "Dijkstra's algorithm finding the shortest collision-free path",
    ),
    "pid-controller": (
        "https://upload.wikimedia.org/wikipedia/commons/d/d4/PD_controller_and_time_response.gif",
        "PD controller response showing overshoot and settling behaviour",
    ),
}


# ── Matplotlib animation library ──────────────────────────────────────────────

def _generate_matplotlib_gif(slug: str, title: str, course_title: str) -> Optional[bytes]:
    """Generate a small animated GIF using matplotlib for the given topic."""
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        import matplotlib.animation as anim
        import numpy as np
        from PIL import Image
    except ImportError:
        logger.warning("matplotlib/PIL not available for offline GIF generation")
        return None

    fig, ax = plt.subplots(figsize=(5, 3), facecolor="#0f1117")
    ax.set_facecolor("#0f1117")
    ax.tick_params(colors="#9ca3af")
    for spine in ax.spines.values():
        spine.set_edgecolor("#374151")

    frames = []
    generated = False

    # ── Sorting array animation ──────────────────────────────────────────────
    if any(k in slug for k in ("sort", "sorting")):
        data = [5, 3, 8, 1, 9, 2, 7, 4, 6]
        n = len(data)
        arr = data[:]
        snapshots = [arr[:]]
        highlights = [(-1, -1)]
        for i in range(n):
            for j in range(0, n - i - 1):
                if arr[j] > arr[j + 1]:
                    arr[j], arr[j + 1] = arr[j + 1], arr[j]
                snapshots.append(arr[:])
                highlights.append((j, j + 1))
        snapshots = snapshots[::max(1, len(snapshots) // 18)]
        highlights = highlights[::max(1, len(highlights) // 18)]

        def draw_sort(frame):
            ax.clear()
            ax.set_facecolor("#0f1117")
            snap = snapshots[min(frame, len(snapshots) - 1)]
            hi = highlights[min(frame, len(highlights) - 1)]
            colors = ["#ef4444" if i in hi else "#3b82f6" for i in range(n)]
            ax.bar(range(n), snap, color=colors, edgecolor="#1f2937", linewidth=0.5)
            ax.set_title(title, color="#e5e7eb", fontsize=9, pad=4)
            ax.set_ylim(0, max(data) + 1)
            ax.set_xticks([])
            ax.set_yticks([])
            for sp in ax.spines.values():
                sp.set_edgecolor("#374151")

        a = anim.FuncAnimation(fig, draw_sort, frames=len(snapshots), interval=300, repeat=True)
        generated = True

    # ── Graph BFS animation ───────────────────────────────────────────────────
    elif any(k in slug for k in ("bfs", "dfs", "graph", "shortest")):
        import networkx as nx
        G = nx.Graph()
        edges = [(0,1),(0,2),(1,3),(1,4),(2,5),(3,6)]
        G.add_edges_from(edges)
        pos = nx.spring_layout(G, seed=42)
        visited_seq = []
        queue = [0]
        seen = {0}
        while queue:
            node = queue.pop(0)
            visited_seq.append(node)
            for nb in sorted(G.neighbors(node)):
                if nb not in seen:
                    seen.add(nb)
                    queue.append(nb)

        def draw_graph(frame):
            ax.clear()
            ax.set_facecolor("#0f1117")
            visited = set(visited_seq[:frame + 1])
            node_colors = ["#ef4444" if n == visited_seq[min(frame, len(visited_seq)-1)]
                           else "#3b82f6" if n in visited else "#374151"
                           for n in G.nodes()]
            nx.draw(G, pos, ax=ax, node_color=node_colors, edge_color="#4b5563",
                    with_labels=True, font_color="#e5e7eb", font_size=8,
                    node_size=400, width=1.5)
            ax.set_title(title, color="#e5e7eb", fontsize=9, pad=4)

        a = anim.FuncAnimation(fig, draw_graph, frames=len(visited_seq) + 1, interval=600, repeat=True)
        generated = True

    # ── Neural network layer animation ────────────────────────────────────────
    elif any(k in slug for k in ("neural", "perceptron", "activation", "layer")):
        layers = [3, 4, 4, 2]
        max_n = max(layers)
        positions = []
        for i, n in enumerate(layers):
            y_start = (max_n - n) / 2.0
            for j in range(n):
                positions.append((i, y_start + j))

        def draw_nn(frame):
            ax.clear()
            ax.set_facecolor("#0f1117")
            ax.set_xlim(-0.5, len(layers) - 0.5)
            ax.set_ylim(-0.5, max_n - 0.5)
            # Draw edges
            offset = 0
            for li, (n1, n2) in enumerate(zip(layers, layers[1:])):
                for j in range(n1):
                    for k in range(n2):
                        p1 = positions[offset + j]
                        p2 = positions[offset + n1 + k]
                        alpha = 0.3 + 0.5 * (abs(frame - li * 3) < 2)
                        ax.plot([p1[0], p2[0]], [p1[1], p2[1]], "-",
                                color="#6b7280", alpha=alpha, linewidth=0.6)
                offset += n1
            # Draw nodes
            for idx, (x, y) in enumerate(positions):
                li = 0
                cnt = 0
                for lj, n in enumerate(layers):
                    if idx < cnt + n:
                        li = lj
                        break
                    cnt += n
                active = abs(frame - li * 3) < 3
                c = "#3b82f6" if active else "#1f2937"
                circle = plt.Circle((x, y), 0.2, color=c, zorder=3)
                ax.add_patch(circle)
            ax.set_title(title, color="#e5e7eb", fontsize=9, pad=4)
            ax.axis("off")

        a = anim.FuncAnimation(fig, draw_nn, frames=18, interval=300, repeat=True)
        generated = True

    # ── Generic wave/signal animation (fallback) ──────────────────────────────
    else:
        import numpy as np
        x = np.linspace(0, 4 * np.pi, 200)

        def draw_wave(frame):
            ax.clear()
            ax.set_facecolor("#0f1117")
            phase = frame * 0.4
            y1 = np.sin(x - phase)
            y2 = 0.5 * np.sin(2 * x - phase)
            ax.plot(x, y1, color="#3b82f6", linewidth=1.5, label="signal")
            ax.plot(x, y2, color="#10b981", linewidth=1, linestyle="--", label="harmonic")
            ax.set_title(title, color="#e5e7eb", fontsize=9, pad=4)
            ax.set_ylim(-1.5, 1.5)
            ax.axhline(0, color="#374151", linewidth=0.5)
            ax.set_xticks([]); ax.set_yticks([])
            for sp in ax.spines.values():
                sp.set_edgecolor("#374151")

        a = anim.FuncAnimation(fig, draw_wave, frames=16, interval=150, repeat=True)
        generated = True

    if not generated:
        plt.close(fig)
        return None

    # Save to temp file then read bytes (PillowWriter requires a file path)
    tmp = tempfile.NamedTemporaryFile(suffix=".gif", delete=False)
    tmp.close()
    try:
        a.save(tmp.name, writer="pillow", fps=3,
               savefig_kwargs={"facecolor": "#0f1117"})
        plt.close(fig)
        with open(tmp.name, "rb") as f:
            return f.read()
    except Exception as exc:
        logger.warning("matplotlib save failed: %s", exc)
        plt.close(fig)
        return None
    finally:
        try:
            os.unlink(tmp.name)
        except OSError:
            pass


def _gif_bytes_to_data_uri(gif_bytes: bytes) -> str:
    b64 = base64.b64encode(gif_bytes).decode("ascii")
    return f"data:image/gif;base64,{b64}"


# ── Strategy B: Gemini-prompted Wikimedia URL ─────────────────────────────────

_WIKIMEDIA_PROMPT = """\
For the topic "{title}" in a {course} course, find the best real animated GIF from Wikimedia Commons.

Output ONLY a JSON object (no markdown fences, no explanation):
{{"url": "https://upload.wikimedia.org/wikipedia/commons/PATH/TO/FILE.gif", "caption": "one sentence"}}

Known working Wikimedia animated GIF examples (use these as style references):
- BFS: https://upload.wikimedia.org/wikipedia/commons/4/46/Animated_BFS.gif
- Bubble sort: https://upload.wikimedia.org/wikipedia/commons/c/c8/Bubble-sort-example-300px.gif
- Merge sort: https://upload.wikimedia.org/wikipedia/commons/c/cc/Merge-sort-example-300px.gif
- Dijkstra: https://upload.wikimedia.org/wikipedia/commons/5/57/Dijkstra_Animation.gif
- AVL tree: https://upload.wikimedia.org/wikipedia/commons/f/fd/AVL_Tree_Example.gif
- Heap sort: https://upload.wikimedia.org/wikipedia/commons/1/1b/Sorting_heapsort_anim.gif
- K-means: https://upload.wikimedia.org/wikipedia/commons/e/ea/K-means_convergence.gif
- Quick sort: https://upload.wikimedia.org/wikipedia/commons/9/9c/Quicksort-example.gif
- Backtracking: https://upload.wikimedia.org/wikipedia/commons/8/8c/Sudoku_solved_by_bactracking.gif
- TCP handshake: https://upload.wikimedia.org/wikipedia/commons/9/98/Tcp-handshake.gif
- Stack: https://upload.wikimedia.org/wikipedia/commons/b/b4/Lifo_stack.gif
- Bloch sphere: https://upload.wikimedia.org/wikipedia/commons/6/6b/Bloch_sphere.gif

Rules:
- MUST end in .gif (not .png, not .svg)
- MUST be a real URL on upload.wikimedia.org that actually exists
- The animation must directly illustrate the core concept
- If no good .gif exists for this specific topic, output: {{"url": null, "caption": null}}
"""


def _try_wikimedia(slug: str, title: str, course_title: str) -> Optional[tuple[str, str]]:
    """Ask Gemini for a Wikimedia GIF URL and verify it."""
    import json as _json
    import urllib.request

    prompt = _WIKIMEDIA_PROMPT.format(title=title, course=course_title)
    raw = _call_api(prompt, MODEL_FLASH, retries=3)
    if not raw:
        return None

    # Parse JSON
    cleaned = re.sub(r"^```(?:json)?\n?", "", raw.strip())
    cleaned = re.sub(r"\n?```$", "", cleaned.strip())
    try:
        data = _json.loads(cleaned)
        url = data.get("url")
        caption = data.get("caption", "")
    except Exception:
        # Try regex fallback
        m = re.search(r'"url"\s*:\s*"(https://upload\.wikimedia\.org/[^"]+\.gif)"', cleaned)
        if not m:
            return None
        url = m.group(1)
        cap_m = re.search(r'"caption"\s*:\s*"([^"]+)"', cleaned)
        caption = cap_m.group(1) if cap_m else title

    if not url or url == "null":
        return None

    # Verify URL exists with HEAD request
    try:
        req = urllib.request.Request(url, method="HEAD",
            headers={"User-Agent": "StudentAI/1.0 (educational)"})
        resp = urllib.request.urlopen(req, timeout=8)
        if resp.status == 200:
            return url, caption
    except Exception as exc:
        logger.debug("URL verification failed for %s: %s", url, exc)

    return None


# ── Injection ─────────────────────────────────────────────────────────────────

_GIF_SECTION = """
## Visual Intuition

![{alt}]({src})
*{caption}*
"""


def _inject_gif_into_page(text: str, src: str, alt: str, caption: str) -> str:
    """Insert ## Visual Intuition section after the first paragraph/quote."""
    section = _GIF_SECTION.format(alt=alt, src=src, caption=caption).strip()

    # If a Visual Intuition section already exists, replace it
    if "## Visual Intuition" in text:
        text = re.sub(
            r"## Visual Intuition\n[\s\S]*?(?=\n## |\Z)",
            section + "\n\n",
            text,
            count=1,
        )
        return text

    # Insert after the title + first quote/paragraph block
    lines = text.split("\n")
    insert_after = 0
    in_front = False
    for i, line in enumerate(lines):
        if line.startswith("# "):
            insert_after = i
            in_front = True
        elif in_front and line.startswith("> "):
            insert_after = i
        elif in_front and line.startswith("## "):
            # Insert before the next section
            break
    insert_at = insert_after + 1
    # Skip blank lines
    while insert_at < len(lines) and not lines[insert_at].strip():
        insert_at += 1
    lines.insert(insert_at, "\n" + section + "\n")
    return "\n".join(lines)


def fix_page_gif(page_path: Path, course_id: str, dry_run: bool = False) -> bool:
    """Add a GIF to a page that's missing one. Returns True if fixed."""
    text = page_path.read_text(encoding="utf-8", errors="ignore")
    slug = page_path.stem
    title_m = re.search(r"^# (.+)$", text, re.MULTILINE)
    title = title_m.group(1).strip() if title_m else slug.replace("-", " ").title()
    course = COURSES_BY_ID.get(course_id)
    course_title = course.title if course else course_id.replace("-", " ").title()

    # Already has a GIF?
    if re.search(r"!\[.*?\]\(https?://.*?\.gif|data:image/gif", text):
        return False
    if re.search(r"!\[.*?\]\(https?://.*?\.(png|jpg|svg)", text) and "## Visual Intuition" in text:
        # Has an image but not animated — still missing GIF
        pass

    logger.info("  Fixing GIF: %s / %s", course_id, slug)

    src = None
    alt = title
    caption = f"Animated illustration of {title}"

    # ── Strategy A: curated lookup ────────────────────────────────────────────
    for key, (url, cap) in WIKIMEDIA_GIFS.items():
        if key in slug or key in title.lower():
            src = url
            caption = cap
            logger.info("    → Strategy A (curated): %s", url[:60])
            break

    # ── Strategy B: Gemini Wikimedia prompt ───────────────────────────────────
    if src is None:
        result = _try_wikimedia(slug, title, course_title)
        if result:
            src, caption = result
            logger.info("    → Strategy B (Gemini+verify): %s", src[:60])
        else:
            logger.info("    → Strategy B failed, using Strategy C (matplotlib)")

    # ── Strategy C: matplotlib animation ─────────────────────────────────────
    if src is None:
        gif_bytes = _generate_matplotlib_gif(slug, title, course_title)
        if gif_bytes:
            src = _gif_bytes_to_data_uri(gif_bytes)
            alt = f"{title} — animated visualization"
            logger.info("    → Strategy C: generated %d byte GIF", len(gif_bytes))
        else:
            logger.warning("    → All strategies failed for %s", slug)
            return False

    # Inject into page
    new_text = _inject_gif_into_page(text, src, alt, caption)
    if not dry_run:
        page_path.write_text(new_text, encoding="utf-8")
    return True


def fix_course(course_id: str, dry_run: bool = False) -> dict:
    """Fix all missing GIFs in a course."""
    wiki_dir = COURSES_DIR / course_id / "wiki"
    if not wiki_dir.exists():
        logger.warning("Course not found: %s", course_id)
        return {}

    pages = [p for p in wiki_dir.glob("*.md")
             if p.name not in ("index.md", "log.md")]
    fixed = 0
    skipped = 0
    _DELAY = 5

    logger.info("\n" + "=" * 60)
    logger.info("  Fixing GIFs: %s  (%d pages)", course_id, len(pages))
    logger.info("=" * 60)

    for page in sorted(pages):
        result = fix_page_gif(page, course_id, dry_run=dry_run)
        if result:
            fixed += 1
            time.sleep(_DELAY)
        else:
            skipped += 1

    logger.info("  Done: fixed=%d  skipped=%d", fixed, skipped)
    return {"fixed": fixed, "skipped": skipped}


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="Fix missing GIFs in course wiki pages.")
    parser.add_argument("--all", action="store_true")
    parser.add_argument("--course-id", nargs="+")
    parser.add_argument("--skip", nargs="+", default=[])
    parser.add_argument("--dry-run", action="store_true", help="Preview without writing")
    args = parser.parse_args()

    results = {}
    skip = set(args.skip)

    if args.course_id:
        for cid in args.course_id:
            results[cid] = fix_course(cid, dry_run=args.dry_run)
    elif args.all:
        for cid in sorted(COURSES_BY_ID.keys()):
            if cid in skip:
                continue
            results[cid] = fix_course(cid, dry_run=args.dry_run)
            time.sleep(3)
    else:
        parser.print_help()
        return

    print("\n" + "=" * 55)
    print("GIF FIX RESULTS:")
    total_fixed = total_skipped = 0
    for cid, r in results.items():
        f, s = r.get("fixed", 0), r.get("skipped", 0)
        total_fixed += f
        total_skipped += s
        print(f"  {cid:<40} fixed={f}  skipped={s}")
    print(f"  {'TOTAL':<40} fixed={total_fixed}  skipped={total_skipped}")
    print("=" * 55)


if __name__ == "__main__":
    main()
